In [2]:
import re
import scipy
import string
import pickle
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder            
from sklearn.svm import LinearSVC             
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier          
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score    
from astropy.table import Table, Column
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.ensemble import BaggingClassifier
from prettytable import PrettyTable
from ipywidgets import widgets



sample_data = pd.read_csv("IRIS.csv")

print("\n\nSample Data:")
print("============\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data)


species=pd.DataFrame({"species":["Iris-setosa","Iris-versicolor","Iris-virginica"]}) 
species_label_encoder = LabelEncoder()
species_label_encoder.fit(np.ravel(species))

sample_data_encoded = sample_data.copy()
original_sample_data = sample_data.copy()

# Transform Output of into Numerical Representation

print("\n\nOutput Attribute After Label Encoding:")
print("========================================\n")
sample_data["encoded_species"] = species_label_encoder.transform(sample_data['species'])
print(sample_data[["species", "encoded_species"]])

# Print Original and Encoded Ouput Sample Data

sample_data_encoded[["sepal_length","sepal_width","petal_length","petal_width","species"]] = sample_data[["sepal_length","sepal_width",
                                                                                                          "petal_length","petal_width","encoded_species"]]
pd.set_option("display.max_rows", None, "display.max_columns", None)
print("\n\nOriginal Sample Data:")
print("=====================\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(original_sample_data)
print("\n\nSample Data after Label Encoding of Output:")
print("===========================================\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded)

# Save the Transformed Features into CSV File 

sample_data_encoded.to_csv(r'sample-data-encoded.csv', index = False, header = True)


training_data_encoded, testing_data_encoded = train_test_split( sample_data_encoded , test_size=0.2 , random_state=0 , shuffle = False)
print("")
print("                    Training Data                            ")
print("")
input_vector_train = training_data_encoded.iloc[: , :-1]
print(input_vector_train)
print("species")
output_label_train = training_data_encoded.iloc[: ,-1]
print(output_label_train)
print("")
print("                    Testing Data                            ")
print("")
input_vector_test = testing_data_encoded.iloc[: , :-1]
print(input_vector_test)
print("species")
output_label_test = testing_data_encoded.iloc[: ,-1]
print(output_label_test)



Sample Data:

     sepal_length  sepal_width  petal_length  petal_width          species
0             5.1          3.5           1.4          0.2      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
4             5.0          3.6           1.4          0.2      Iris-setosa
5             5.4          3.9           1.7          0.4      Iris-setosa
6             4.6          3.4           1.4          0.3      Iris-setosa
7             5.0          3.4           1.5          0.2      Iris-setosa
8             4.4          2.9           1.4          0.2      Iris-setosa
9             4.9          3.1           1.5          0.1      Iris-setosa
10            5.4          3.7           1.5          0.2      Iris-setosa
11            4.8          3.4           1.6          0.2      Iris-setosa
12       

In [3]:
logistic_regression=LogisticRegression()
logistic_regression.fit(input_vector_train,output_label_train)
logistic_regression_prediction=logistic_regression.predict(input_vector_test)
predict=logistic_regression_prediction
print(predict)
lr_accuracy=accuracy_score(output_label_test,logistic_regression_prediction)

print(lr_accuracy)


[2 2 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.8333333333333334


In [4]:
Random_Forest_Classifier=RandomForestClassifier()
Random_Forest_Classifier.fit(input_vector_train,output_label_train)
Random_Forest_Classifier_prediction=Random_Forest_Classifier.predict(input_vector_test)
predict=Random_Forest_Classifier_prediction
print(predict)
rfc_accuracy=accuracy_score(output_label_test,Random_Forest_Classifier_prediction)
print(rfc_accuracy)


[2 1 2 1 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.7333333333333333


In [5]:
linearsvc=LinearSVC(max_iter=10000)
linearsvc.fit(input_vector_train,output_label_train)
linearsvc_prediction=linearsvc.predict(input_vector_test)
predict=linearsvc_prediction
print(predict)
lsvc_accuracy=accuracy_score(output_label_test,linearsvc_prediction)
print(lsvc_accuracy)

[2 2 2 1 2 1 1 1 2 1 1 1 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.6666666666666666


In [6]:
bernoullinb=BernoulliNB()
bernoullinb.fit(input_vector_train,output_label_train)
bernoullinb_prediction=bernoullinb.predict(input_vector_test)
predict=bernoullinb_prediction
print(predict)
bnb_accuracy=accuracy_score(output_label_test,bernoullinb_prediction)
print(bnb_accuracy)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0.0


In [7]:
decisiontree=tree.DecisionTreeClassifier()
decisiontree.fit(input_vector_train,output_label_train)
decisiontree_prediction=decisiontree.predict(input_vector_test)
predict=decisiontree_prediction
print(predict)
dt_accuracy=accuracy_score(output_label_test,decisiontree_prediction)

print(dt_accuracy)


[2 2 2 2 2 2 2 1 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.9


In [8]:
kneighbors=KNeighborsClassifier(n_neighbors=7)
kneighbors.fit(input_vector_train,output_label_train)
kneighbors_prediction=kneighbors.predict(input_vector_test)
predict=kneighbors_prediction
print(predict)
knn_accuracy=accuracy_score(output_label_test,kneighbors_prediction)

print(knn_accuracy)


[2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.8


In [9]:
gaussian_nb=GaussianNB()
gaussian_nb.fit(input_vector_train,output_label_train)
gaussian_nb_prediction=gaussian_nb.predict(input_vector_test)
predict=gaussian_nb_prediction
print(predict)
gnb_accuracy=accuracy_score(output_label_test,gaussian_nb_prediction)
print(gnb_accuracy)


[2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
0.9333333333333333


In [10]:
svc=SVC()
svc.fit(input_vector_train,output_label_train)
svc_prediction=svc.predict(input_vector_test)
predict=svc_prediction
print(predict)
svc_accuracy=accuracy_score(output_label_test,svc_prediction)

print(svc_accuracy)


[2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2 2 1]
0.7


In [11]:
gradientboosting=GradientBoostingClassifier()
gradientboosting.fit(input_vector_train,output_label_train)
gradientboosting_prediction=gradientboosting.predict(input_vector_test)
predict=gradientboosting_prediction
print(predict)
gb_accuracy=accuracy_score(output_label_test,gradientboosting_prediction)

print(gb_accuracy)


[2 1 2 1 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.7333333333333333


In [12]:
baggingclassifier=BaggingClassifier()
baggingclassifier.fit(input_vector_train,output_label_train)
baggingclassifier_prediction=baggingclassifier.predict(input_vector_test)
predict=baggingclassifier_prediction
print(predict)
bc_accuracy=accuracy_score(output_label_test,baggingclassifier_prediction)

print(bc_accuracy)


[2 1 2 1 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
0.7333333333333333


In [13]:
x=PrettyTable()
x.field_names=["Model","Accuracy"]
x.add_row(["LogisticRegression",lr_accuracy.round(2)])
x.add_row(["RandomForestClassifier",rfc_accuracy.round(2)])
x.add_row(["LinearSVC,LogisticRegression",lr_accuracy.round(2)])
x.add_row(["BernoulliNB",lsvc_accuracy.round(2)])
x.add_row(["DecisionTreeClassifier",dt_accuracy.round(2)])
x.add_row(["KNeighborsClassifier",knn_accuracy.round(2)])
x.add_row(["GaussianNB",gnb_accuracy.round(2)])
x.add_row(["SVC",svc_accuracy.round(2)])
x.add_row(["GradientBoostingClassifier",gb_accuracy.round(2)])
x.add_row(["BaggingClassifier",bc_accuracy.round(2)])
print(x)

+------------------------------+----------+
|            Model             | Accuracy |
+------------------------------+----------+
|      LogisticRegression      |   0.83   |
|    RandomForestClassifier    |   0.73   |
| LinearSVC,LogisticRegression |   0.83   |
|         BernoulliNB          |   0.67   |
|    DecisionTreeClassifier    |   0.9    |
|     KNeighborsClassifier     |   0.8    |
|          GaussianNB          |   0.93   |
|             SVC              |   0.7    |
|  GradientBoostingClassifier  |   0.73   |
|      BaggingClassifier       |   0.73   |
+------------------------------+----------+


In [14]:
model_save=open("gaussian_model.pkl","wb")
pickle.dump(gaussian_nb,model_save)
model_save.close()